version: "3"
name: Chat
services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat
    ports:
      - "3307:3306"
    volumes:
      - "./database/create.sql:/docker-entrypoint-initdb.d/1.sql"

  backend:
    build: ./server
    container_name: server
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=chat
